"""
estimate.jl — Two-step estimation of (γ, κ, φ) from `data/simulated_data.csv`.

Step 1 NLS for γ using deterministic Cournot quantities; Step 2 NelderMead
MLE for (κ, φ) given γ̂, using a stage-replay likelihood. BHHH standard
errors at the optimum. Starting values are deliberately far from the true
calibration so the optimizer has to traverse the parameter space.
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

include(joinpath(@__DIR__, "../src/MiniProject.jl"))
using .MiniProject
using CSV, DataFrames, Printf

const DATA_PATH = joinpath(@__DIR__, "../../data/simulated_data.csv")

println("Loading $DATA_PATH")
df = CSV.read(DATA_PATH, DataFrame)
println("  $(nrow(df)) rows, $(length(unique(df.market_id))) markets")

println("\nRecovering per-market states and action counts …")
markets = recover_markets(df)
println("  recovered $(length(markets)) markets")

p_base = default_params()
println("\nBase parameters (γ, κ, φ are overwritten by estimation):")
@printf("  true γ = (%.3f, %.3f, %.3f), κ = %.3f, φ = %.3f\n",
        p_base.gamma[1], p_base.gamma[2], p_base.gamma[3],
        p_base.kappa, p_base.phi)

# ── Step 1: NLS for γ ────────────────────────────────────────────────────────
println("\n=== Step 1: NLS for γ (start γ⁰ = (0,0,0)) ===")
γ̂, ss = nls_gamma(markets, p_base; gamma0 = (0.0, 0.0, 0.0), trace = false)
@printf("  γ̂ = (%.6f, %.6f, %.6f)\n", γ̂[1], γ̂[2], γ̂[3])
@printf("  min SSR = %.3e\n", ss)

# ── Step 2: MLE for (κ, φ) ──────────────────────────────────────────────────
println("\n=== Step 2: MLE for (κ, φ) given γ̂ (start (κ⁰,φ⁰) = (1.0, 1.0)) ===")
κ̂, φ̂, ℓ̂, res = mle_kappa_phi(markets, γ̂, p_base;
                                kappa0 = 1.0, phi0 = 1.0, trace = true)
@printf("\n  κ̂ = %.4f    φ̂ = %.4f    ℓ̂ = %.3f\n", κ̂, φ̂, ℓ̂)

# ── BHHH standard errors ────────────────────────────────────────────────────
println("\n=== BHHH standard errors at (κ̂, φ̂, γ̂) ===")
p_hat = Params(p_base.A, p_base.B, p_base.M, p_base.c_o, p_base.c_n0,
               p_base.beta, κ̂, φ̂, p_base.sigma, γ̂, p_base.rho, p_base.N_max,
               p_base.blocs, p_base.subsidy)
se = bhhh_se(markets, p_hat; step = 1e-4)
@printf("  SE(κ) = %.4f    SE(φ) = %.4f\n", se.se_kappa, se.se_phi)

# ── Summary table ───────────────────────────────────────────────────────────
println("\n=== Summary ===")
@printf("%-8s %10s %10s %10s\n", "param", "truth", "estimate", "s.e.")
@printf("%-8s %10.4f %10.4f %10s\n", "κ",  p_base.kappa, κ̂, @sprintf("%.4f", se.se_kappa))
@printf("%-8s %10.4f %10.4f %10s\n", "φ",  p_base.phi,   φ̂, @sprintf("%.4f", se.se_phi))
@printf("%-8s %10.4f %10.4f %10s\n", "γ₁", p_base.gamma[1], γ̂[1], "—")
@printf("%-8s %10.4f %10.4f %10s\n", "γ₂", p_base.gamma[2], γ̂[2], "—")
@printf("%-8s %10.4f %10.4f %10s\n", "γ₃", p_base.gamma[3], γ̂[3], "—")


# ── Export LaTeX macros + results table ─────────────────────────────────────
const OUT_EST = joinpath(@__DIR__, "../../output/estimates")
const OUT_TAB = joinpath(@__DIR__, "../../output/tables")
mkpath(OUT_EST); mkpath(OUT_TAB)

open(joinpath(OUT_EST, "estimation.txt"), "w") do io
    println(io, "% Auto-generated by code/scripts/estimate.jl")
    @printf(io, "\\newcommand{\\InnovCostTrue}{%.4f}\n",   p_base.kappa)
    @printf(io, "\\newcommand{\\InnovCostHat}{%.4f}\n",    κ̂)
    @printf(io, "\\newcommand{\\InnovCostSe}{%.4f}\n",     se.se_kappa)
    @printf(io, "\\newcommand{\\EntryCostTrue}{%.4f}\n",   p_base.phi)
    @printf(io, "\\newcommand{\\EntryCostHat}{%.4f}\n",    φ̂)
    @printf(io, "\\newcommand{\\EntryCostSe}{%.4f}\n",     se.se_phi)
    @printf(io, "\\newcommand{\\SpilloverOneTrue}{%.4f}\n",   p_base.gamma[1])
    @printf(io, "\\newcommand{\\SpilloverOneHat}{%.4f}\n",    γ̂[1])
    @printf(io, "\\newcommand{\\SpilloverTwoTrue}{%.4f}\n",   p_base.gamma[2])
    @printf(io, "\\newcommand{\\SpilloverTwoHat}{%.4f}\n",    γ̂[2])
    @printf(io, "\\newcommand{\\SpilloverThreeTrue}{%.4f}\n", p_base.gamma[3])
    @printf(io, "\\newcommand{\\SpilloverThreeHat}{%.4f}\n",  γ̂[3])
    @printf(io, "\\newcommand{\\NlsSsr}{%.2e}\n",          ss)
    @printf(io, "\\newcommand{\\LogLikHat}{%.3f}\n",       ℓ̂)
    @printf(io, "\\newcommand{\\NumMarkets}{%d}\n",        length(markets))
end
println("Wrote $(joinpath(OUT_EST, "estimation.txt"))")

open(joinpath(OUT_TAB, "estimation.tex"), "w") do io
    println(io, "% Auto-generated by code/scripts/estimate.jl")
    println(io, "\\begin{tabular}{lccc}")
    println(io, "\\toprule")
    println(io, "Parameter & Truth & Estimate & S.E. \\\\")
    println(io, "\\midrule")
    @printf(io, "\$\\kappa\$   & %.4f & %.4f & %.4f \\\\\n",
            p_base.kappa, κ̂, se.se_kappa)
    @printf(io, "\$\\phi\$     & %.4f & %.4f & %.4f \\\\\n",
            p_base.phi,   φ̂, se.se_phi)
    @printf(io, "\$\\gamma_1\$ & %.4f & %.4f & --- \\\\\n",
            p_base.gamma[1], γ̂[1])
    @printf(io, "\$\\gamma_2\$ & %.4f & %.4f & --- \\\\\n",
            p_base.gamma[2], γ̂[2])
    @printf(io, "\$\\gamma_3\$ & %.4f & %.4f & --- \\\\\n",
            p_base.gamma[3], γ̂[3])
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
end
println("Wrote $(joinpath(OUT_TAB, "estimation.tex"))")

println("\nDone.")
