"""
run_2period.jl — Solve the 2-period Igami model with agglomeration.

Outputs:
  - CCPs at initial state s0 = (4,1,1,2) for baseline (γ=0) and γ=0.05
  - Comparative statics: P(innovate|old, s0) vs γ  →  output/figures/
  - Key scalars exported as LaTeX macros              →  output/estimates/
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

push!(LOAD_PATH, joinpath(@__DIR__, "../src"))
include(joinpath(@__DIR__, "../src/Igami2017.jl"))
using .Igami2017
using Plots, Printf, DataFrames

# ── Directories ──────────────────────────────────────────────────────────────
const OUTPUT_DIR = joinpath(@__DIR__, "../../output")
mkpath(joinpath(OUTPUT_DIR, "figures"))
mkpath(joinpath(OUTPUT_DIR, "estimates"))
mkpath(joinpath(OUTPUT_DIR, "tables"))

# ── Initial state of interest ────────────────────────────────────────────────
# Inspired by early HDD market: several old incumbents, a few innovative firms
const S0 = State(4, 1, 1, 2)   # (n_o, n_b, n_n, n_pe)

# ── Verification: Cournot check ───────────────────────────────────────────────
println("=== Cournot verification ===")
p_check = default_params(gamma=0.0)
# Symmetric N-firm Cournot: q = M*(A-c)/(B*(N+1)), π = B/M * q^2
N_sym = 4; c_sym = 0.5
q_sym_formula = p_check.M * (p_check.A - c_sym) / (p_check.B * (N_sym + 1))
pi_sym_formula = (p_check.B / p_check.M) * q_sym_formula^2
_, pi_sym_code = cournot_profits(0, N_sym, p_check.c_o, c_sym, p_check)
@printf("  N=%d symmetric (c=%.2f): formula=%.4f, code=%.4f  [%s]\n",
        N_sym, c_sym, pi_sym_formula, pi_sym_code,
        abs(pi_sym_formula - pi_sym_code) < 1e-10 ? "PASS" : "FAIL")

# ── Solve baseline (γ = 0) ────────────────────────────────────────────────────
println("\n=== Baseline model (γ = 0) ===")
p0   = default_params(gamma=0.0)
V1_0, ccps_0 = solve_2period(p0)
c0   = ccps_0[S0]
@printf("  s0 = (%d,%d,%d,%d)\n", S0.n_o, S0.n_b, S0.n_n, S0.n_pe)
@printf("  P(innovate|old) = %.4f\n", c0.p_io)
@printf("  P(stay|old)     = %.4f\n", c0.p_so)
@printf("  P(enter|pe)     = %.4f\n", c0.p_ep)

# ── Solve agglomeration model (γ = 0.05) ─────────────────────────────────────
println("\n=== Agglomeration model (γ = 0.05) ===")
p1   = default_params(gamma=0.05)
V1_1, ccps_1 = solve_2period(p1)
c1   = ccps_1[S0]
@printf("  P(innovate|old) = %.4f\n", c1.p_io)
@printf("  P(stay|old)     = %.4f\n", c1.p_so)
@printf("  P(enter|pe)     = %.4f\n", c1.p_ep)

# ── Comparative statics: P(innovate|old, s0) vs γ ────────────────────────────
println("\n=== Comparative statics ===")
gamma_grid = 0.0:0.01:0.3
p_innov = Float64[]
p_enter = Float64[]

for γ in gamma_grid
    p_γ = default_params(gamma=γ)
    _, ccps_γ = solve_2period(p_γ)
    c_γ = ccps_γ[S0]
    push!(p_innov, c_γ.p_io)
    push!(p_enter, c_γ.p_ep)
end

# ── Plot ──────────────────────────────────────────────────────────────────────
plt = plot(
    collect(gamma_grid), [p_innov p_enter],
    label  = ["P(innovate | old)" "P(enter | pe)"],
    xlabel = "Agglomeration parameter γ",
    ylabel = "Probability",
    title  = "CCPs vs Agglomeration (s₀ = (4,1,1,2))",
    lw     = 2,
    legend = :right,
    grid   = true
)

fig_path = joinpath(OUTPUT_DIR, "figures", "comp_stats_agglomeration.pdf")
savefig(plt, fig_path)
println("  Figure saved to: $fig_path")

# ── Summary table ─────────────────────────────────────────────────────────────
df = DataFrame(
    gamma     = collect(gamma_grid)[1:5:end],
    p_innov   = p_innov[1:5:end],
    p_enter   = p_enter[1:5:end]
)
println("\n  Sample of comparative statics:")
println("  ", df)

# Export LaTeX table
tex_table = """\\begin{tabular}{ccc}
\\hline
\$\\gamma\$ & \$P(\\text{innovate} | \\text{old})\$ & \$P(\\text{enter} | \\text{pe})\$ \\\\
\\hline
"""
for row in eachrow(df)
    global tex_table *= @sprintf("%.2f & %.4f & %.4f \\\\\n", row.gamma, row.p_innov, row.p_enter)
end
tex_table *= "\\hline\n\\end{tabular}"

table_path = joinpath(OUTPUT_DIR, "tables", "comp_stats_agglomeration.tex")
open(table_path, "w") do f
    write(f, tex_table)
end
println("\n  Table saved to: $table_path")

# ── Export key scalars as LaTeX macros ────────────────────────────────────────
macros = """% 2-period Igami model with agglomeration — key estimates
% Generated by run_2period.jl
\\newcommand{\\pInnovatBaseline}{$(round(ccps_0[S0].p_io, digits=4))}
\\newcommand{\\pInnovatAgglom}{$(round(ccps_1[S0].p_io, digits=4))}
\\newcommand{\\pEnterBaseline}{$(round(ccps_0[S0].p_ep, digits=4))}
\\newcommand{\\pEnterAgglom}{$(round(ccps_1[S0].p_ep, digits=4))}
\\newcommand{\\gammaAgglom}{0.05}
"""

macro_path = joinpath(OUTPUT_DIR, "estimates", "2period_estimates.txt")
open(macro_path, "w") do f
    write(f, macros)
end
println("  Macros saved to: $macro_path")

println("\nDone.")
