"""
run_regional.jl — Solve the 2-period Igami model with *regional* agglomeration.

Produces:
  - CCPs at an initial state under (a) uniform baseline γ, (b) a region-1
    subsidy counterfactual, and (c) an initial-cluster counterfactual
  - A regional comparative-statics figure (P(innovate|old, r) vs γ₁)
  - LaTeX macros + table consumed by writeup/progress_agglomeration.tex
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

push!(LOAD_PATH, joinpath(@__DIR__, "../src"))
include(joinpath(@__DIR__, "../src/MiniProject.jl"))
using .MiniProject
using Plots, Printf, DataFrames

# ── Directories ──────────────────────────────────────────────────────────────
const OUTPUT_DIR = joinpath(@__DIR__, "../../output")
mkpath(joinpath(OUTPUT_DIR, "figures"))
mkpath(joinpath(OUTPUT_DIR, "estimates"))
mkpath(joinpath(OUTPUT_DIR, "tables"))

# ── Initial states (each with total ≤ N_max) ────────────────────────────────
# S0_SYM: 1 old + 1 "both" per region, no entrants yet. Total = 6.
const S0_SYM = State((1, 1, 1), (1, 1, 1), (0, 0, 0), (0, 0, 0))

# S0_CLUST: same total industry but all 3 innovators clustered in region 1.
const S0_CLUST = State((1, 1, 1), (3, 0, 0), (0, 0, 0), (0, 0, 0))

# ── Cournot regional sanity: all firms in region 1 should match symmetric ────
println("=== Cournot regional sanity ===")
p_check = default_params(gamma=0.0, rho=0.0, N_max=6)
pi_o_r, pi_b_r, pi_n_r = cournot_profits_regional(
    (2, 0, 0), (1, 0, 0), (1, 0, 0), 1.5, (0.5, 0.5, 0.5), p_check)
pi_o, pi_b, pi_n = cournot_profits(2, 1, 1, 1.5, 0.5, p_check)
@printf("  single-region collapse matches symmetric: %s\n",
        all(abs.((pi_o_r[1]-pi_o, pi_b_r[1]-pi_b, pi_n_r[1]-pi_n)) .< 1e-10) ?
        "PASS" : "FAIL")

# ── Baseline: uniform γ ──────────────────────────────────────────────────────
println("\n=== Baseline (uniform γ = 0.05, symmetric initial state) ===")
p_base = default_params(gamma=0.05, rho=0.5, N_max=6)
@time _, c_base = solve_initial(S0_SYM, p_base)
@printf("  p_io (per region) = (%.4f, %.4f, %.4f)\n", c_base.p_io...)
@printf("  p_so (per region) = (%.4f, %.4f, %.4f)\n", c_base.p_so...)
@printf("  p_ep (per region) = (%.4f, %.4f, %.4f)\n", c_base.p_ep...)

# ── Counterfactual 1: subsidize region 1 ─────────────────────────────────────
println("\n=== Counterfactual A: subsidize region 1 (γ = (0.15, 0.05, 0.05)) ===")
p_cfA = default_params(gamma=(0.15, 0.05, 0.05), rho=0.5, N_max=6)
@time _, c_cfA = solve_initial(S0_SYM, p_cfA)
@printf("  p_io = (%.4f, %.4f, %.4f)\n", c_cfA.p_io...)
@printf("  p_ep = (%.4f, %.4f, %.4f)\n", c_cfA.p_ep...)

# ── Counterfactual 2: initial-cluster concentration in region 1 ──────────────
println("\n=== Counterfactual B: initial innovators clustered in region 1 ===")
p_cfB = default_params(gamma=0.05, rho=0.5, N_max=6)
@time _, c_cfB = solve_initial(S0_CLUST, p_cfB)
@printf("  p_io = (%.4f, %.4f, %.4f)\n", c_cfB.p_io...)

# ── Comparative statics: P(innovate|old, r) vs γ₁ ────────────────────────────
println("\n=== Comparative statics: γ₁ sweep ===")
gamma1_grid = 0.0:0.02:0.20
p_io_r1 = Float64[]; p_io_r2 = Float64[]; p_io_r3 = Float64[]
for γ1 in gamma1_grid
    p_γ = default_params(gamma=(γ1, 0.05, 0.05), rho=0.5, N_max=6)
    _, cγ = solve_initial(S0_SYM, p_γ)
    push!(p_io_r1, cγ.p_io[1])
    push!(p_io_r2, cγ.p_io[2])
    push!(p_io_r3, cγ.p_io[3])
end

plt = plot(
    collect(gamma1_grid), [p_io_r1 p_io_r2 p_io_r3],
    label  = ["Region 1 (treated)" "Region 2" "Region 3"],
    xlabel = "γ₁ (region-1 agglomeration strength)",
    ylabel = "P(innovate | old, r)",
    title  = "Regional subsidy: own-region gain vs spillover drag",
    lw     = 2,
    legend = :right,
    grid   = true
)
fig_path = joinpath(OUTPUT_DIR, "figures", "regional_subsidy.pdf")
savefig(plt, fig_path)
println("  Figure saved to: $fig_path")

# ── Summary table ────────────────────────────────────────────────────────────
df = DataFrame(
    Scenario = ["Baseline", "CS-A: subsidy r1", "CS-B: cluster r1"],
    p_io_r1  = [c_base.p_io[1], c_cfA.p_io[1], c_cfB.p_io[1]],
    p_io_r2  = [c_base.p_io[2], c_cfA.p_io[2], c_cfB.p_io[2]],
    p_io_r3  = [c_base.p_io[3], c_cfA.p_io[3], c_cfB.p_io[3]],
)
println("\n  Summary:")
println("  ", df)

tex_table = """\\begin{tabular}{lccc}
\\hline
Scenario & \$P(\\text{innov}|o,r{=}1)\$ & \$P(\\text{innov}|o,r{=}2)\$ & \$P(\\text{innov}|o,r{=}3)\$ \\\\
\\hline
"""
for row in eachrow(df)
    global tex_table *= @sprintf("%s & %.4f & %.4f & %.4f \\\\\n",
                                  row.Scenario, row.p_io_r1, row.p_io_r2, row.p_io_r3)
end
tex_table *= "\\hline\n\\end{tabular}"
table_path = joinpath(OUTPUT_DIR, "tables", "regional_comp_stats.tex")
open(table_path, "w") do f; write(f, tex_table); end
println("\n  Table saved to: $table_path")

# ── LaTeX macros ─────────────────────────────────────────────────────────────
fmt4(x) = @sprintf("%.4f", x)
macros = """% 2-period Igami model with *regional* agglomeration — key estimates
% Generated by run_regional.jl
\\newcommand{\\pInnovBaselineROne}{$(fmt4(c_base.p_io[1]))}
\\newcommand{\\pInnovBaselineRTwo}{$(fmt4(c_base.p_io[2]))}
\\newcommand{\\pInnovBaselineRThree}{$(fmt4(c_base.p_io[3]))}
\\newcommand{\\pInnovSubsidyROne}{$(fmt4(c_cfA.p_io[1]))}
\\newcommand{\\pInnovSubsidyRTwo}{$(fmt4(c_cfA.p_io[2]))}
\\newcommand{\\pInnovSubsidyRThree}{$(fmt4(c_cfA.p_io[3]))}
\\newcommand{\\pInnovClusterROne}{$(fmt4(c_cfB.p_io[1]))}
\\newcommand{\\pInnovClusterRTwo}{$(fmt4(c_cfB.p_io[2]))}
\\newcommand{\\pInnovClusterRThree}{$(fmt4(c_cfB.p_io[3]))}
\\newcommand{\\gammaSubsidyOne}{0.15}
\\newcommand{\\gammaOther}{0.05}
"""
macro_path = joinpath(OUTPUT_DIR, "estimates", "regional_estimates.txt")
open(macro_path, "w") do f; write(f, macros); end
println("  Macros saved to: $macro_path")

println("\nDone.")
