"""
summary_stats.jl — Per-region and pooled means for the simulated panel.

Reads `data/simulated_data.csv` and reports, per region (1=US, 2=EU,
3=RoW) and across all regions:
  - innovation rate         P(innovate | old, period=1)
  - entry rate              P(enter | pe, period=1)
  - avg n_o per market      period-1 mean count of old firms
  - avg n_pe per market     period-1 mean count of potential entrants
  - avg period-2 n_n        mean count of new firms in period 2

The "Total" column pools across regions for rates and sums regional
means for counts.

Outputs:
  - output/estimates/summary_stats.txt   LaTeX macros (camelCase)
  - output/tables/summary_stats.tex      bare booktabs tabular
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using CSV, DataFrames, Printf, Statistics

# ── Paths ───────────────────────────────────────────────────────────────────
const DATA_PATH = joinpath(@__DIR__, "../../data/simulated_data.csv")
const OUTPUT_DIR = joinpath(@__DIR__, "../../output")
const OUT_EST    = joinpath(OUTPUT_DIR, "estimates")
const OUT_TAB    = joinpath(OUTPUT_DIR, "tables")
mkpath(OUT_EST); mkpath(OUT_TAB)

# ── Load data ───────────────────────────────────────────────────────────────
df = CSV.read(DATA_PATH, DataFrame)

# ── Helpers ─────────────────────────────────────────────────────────────────
"""Share of `firm_type` rows in `period` of given `region` whose action
equals `action`. `region = 0` pools across regions."""
function action_rate(df, period::Int, region::Int, firm_type::String, action::String)
    mask = (df.period .== period) .& (df.firm_type .== firm_type)
    if region != 0
        mask = mask .& (df.region .== region)
    end
    sub = df[mask, :]
    nrow(sub) == 0 ? NaN : count(sub.action .== action) / nrow(sub)
end

"""Mean per-market count of `firm_type` rows in `period` of given `region`.
`region = 0` returns the sum of regional means."""
function mean_count_per_market(df, period::Int, region::Int, firm_type::String)
    mask = (df.period .== period) .& (df.firm_type .== firm_type)
    if region != 0
        mask = mask .& (df.region .== region)
        sub = df[mask, :]
        n_markets = length(unique(df.market_id))
        return nrow(sub) / n_markets
    else
        return sum(mean_count_per_market(df, period, r, firm_type) for r in 1:3)
    end
end

# ── Compute table ───────────────────────────────────────────────────────────
const REGIONS = (1, 2, 3, 0)  # 0 = total

innov_rate = [action_rate(df, 1, r, "old", "innovate") for r in REGIONS]
entry_rate = [action_rate(df, 1, r, "pe", "enter")    for r in REGIONS]
avg_no     = [mean_count_per_market(df, 1, r, "old")  for r in REGIONS]
avg_npe    = [mean_count_per_market(df, 1, r, "pe")   for r in REGIONS]
avg_nn_p2  = [mean_count_per_market(df, 2, r, "new")  for r in REGIONS]

n_markets = length(unique(df.market_id))

@printf("Markets: %d\n", n_markets)
@printf("Innovation rate: R1=%.3f R2=%.3f R3=%.3f Total=%.3f\n", innov_rate...)
@printf("Entry rate:      R1=%.3f R2=%.3f R3=%.3f Total=%.3f\n", entry_rate...)
@printf("Avg n_o:         R1=%.2f R2=%.2f R3=%.2f Total=%.2f\n", avg_no...)
@printf("Avg n_pe:        R1=%.2f R2=%.2f R3=%.2f Total=%.2f\n", avg_npe...)
@printf("Avg period-2 n_n:R1=%.2f R2=%.2f R3=%.2f Total=%.2f\n", avg_nn_p2...)

# ── Macros ──────────────────────────────────────────────────────────────────
const TAGS = ("ROne", "RTwo", "RThree", "Total")

open(joinpath(OUT_EST, "summary_stats.txt"), "w") do io
    println(io, "% Auto-generated by code/scripts/summary_stats.jl")
    @printf(io, "\\newcommand{\\SummaryNMarkets}{%d}\n", n_markets)
    for (i, tag) in enumerate(TAGS)
        @printf(io, "\\newcommand{\\InnovRate%s}{%.3f}\n", tag, innov_rate[i])
    end
    for (i, tag) in enumerate(TAGS)
        @printf(io, "\\newcommand{\\EntryRate%s}{%.3f}\n", tag, entry_rate[i])
    end
    for (i, tag) in enumerate(TAGS)
        @printf(io, "\\newcommand{\\AvgNo%s}{%.2f}\n", tag, avg_no[i])
    end
    for (i, tag) in enumerate(TAGS)
        @printf(io, "\\newcommand{\\AvgNpe%s}{%.2f}\n", tag, avg_npe[i])
    end
    for (i, tag) in enumerate(TAGS)
        @printf(io, "\\newcommand{\\AvgNn%s}{%.2f}\n", tag, avg_nn_p2[i])
    end
    @printf(io, "\\newcommand{\\EntryInnovGapPP}{%.1f}\n",
            100 * (entry_rate[end] - innov_rate[end]))
end

# ── Tabular ─────────────────────────────────────────────────────────────────
open(joinpath(OUT_TAB, "summary_stats.tex"), "w") do io
    println(io, "% Auto-generated by code/scripts/summary_stats.jl")
    println(io, "\\begin{tabular}{lcccc}")
    println(io, "  \\toprule")
    println(io, "                       & Region 1 (US) & Region 2 (EU) & Region 3 (RoW) & Total \\\\")
    println(io, "  \\midrule")
    @printf(io, "  Innovation rate      & %.3f & %.3f & %.3f & %.3f \\\\\n", innov_rate...)
    @printf(io, "  Entry rate           & %.3f & %.3f & %.3f & %.3f \\\\\n", entry_rate...)
    @printf(io, "  Avg.\\ \$n_o\$ per market   & %.2f & %.2f & %.2f & %.2f \\\\\n", avg_no...)
    @printf(io, "  Avg.\\ \$n_{pe}\$ per market & %.2f & %.2f & %.2f & %.2f \\\\\n", avg_npe...)
    @printf(io, "  Avg.\\ period-2 \$n_n\$       & %.2f & %.2f & %.2f & %.2f \\\\\n", avg_nn_p2...)
    println(io, "  \\bottomrule")
    println(io, "\\end{tabular}")
end

println("\nWrote $(joinpath(OUT_EST, "summary_stats.txt"))")
println("Wrote $(joinpath(OUT_TAB, "summary_stats.tex"))")
